# -*- coding: utf-8 -*-
"""Nilai eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEl4xaqVaEnmTym1ifKIE5YTk3cnx1m3
"""

import numpy as np


# Mencari nilai eigen dan vektor eigen
A = np.array([[4, 1],
              [2, 1]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as np


# Mencari nilai eigen dan vektor eigen
V = np.array([[6, 7, 0],
              [-3, 0,-2]])
nilaieigen, vektoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)