# -*- coding: utf-8 -*-
"""pertumbuhan logistik.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtIordiQghE36cYXAx-H5rofmEfQjzvR

kodingan Pertumbuhan Logiatik stok obat-obatan
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameter Masalah
K = 1000   # Kapasitas maksimum distribusi obat dalam t
r = 0.1    # Laju distribusi obat
P0 = 100   # Jumlah obat yang tersedia di awal
t_max = 30 # waktu yang dihitung dalam hari

# Waktu yang dihitung (hari)
t = np.linspace(0, t_max, t_max + 1)

# Fungsi untuk menghitung stok obat berdasarkan rumus logistik
def logistic_growth(K, r, P0, t):
    return K / (1 + ((K - P0) / P0) * np.exp(-r * t))

# Menghitung stok obat selama 30 hari
P = logistic_growth(K, r, P0, t)

# Plot hasil simulasi
plt.figure(figsize=(8, 5))
plt.plot(t, P, label="Distribusi Obat", color='b')
plt.axhline(K, linestyle="--", color='r', label="Kapasitas Maksimum (K)")
plt.xlabel("Waktu (Hari)")
plt.ylabel("Jumlah Obat yang Terdistribusi")
plt.title("Model Pertumbuhan Logistik untuk Persediaan Obat")
plt.legend()
plt.grid()
plt.show()