# -*- coding: utf-8 -*-
"""Tugas_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174Or_zrdEWpYgHzXszt-W8uH8QvFf_8Q

Model SIR dengan penambahan kelahiran dan kematian
"""

import matplotlib.pyplot as plt
from scipy.integrate import odeint
import ipywidgets as widgets
from IPython.display import display
import numpy as np

# Model SIR dengan kelahiran dan kematian
def sir_model_birth_death(y, t, N, beta, gamma, alpha, sigma):
    S, I, R = y
    dSdt = alpha * N - beta * S * I / N - sigma * S
    dIdt = beta * S * I / N - gamma * I - sigma * I
    dRdt = gamma * I - sigma * R
    return [dSdt, dIdt, dRdt]

# Fungsi untuk memperbarui grafik
def update_sir_birth_death(beta, gamma, alpha, sigma, S0, I0, Tmax):
    N = S0 + I0  # Total populasi
    R0 = 0  # Tidak ada yang sembuh pada awalnya
    t = np.linspace(0, Tmax, Tmax)  # Waktu simulasi

    # Menyelesaikan sistem persamaan diferensial
    y0 = [S0, I0, R0]
    solution = odeint(sir_model_birth_death, y0, t, args=(N, beta, gamma, alpha, sigma))
    S, I, R = solution.T

    # Plot hasil simulasi
    plt.figure(figsize=(10, 6))
    plt.plot(t, S, label='Susceptible', color='blue')
    plt.plot(t, I, label='Infected', color='orange')
    plt.plot(t, R, label='Removed', color='green')
    plt.xlabel('Hari')
    plt.ylabel('Jumlah Individu')
    plt.title('Simulasi Model SIR dengan Kelahiran dan Kematian')
    plt.legend()
    plt.grid()
    plt.show()

# Membuat slider interaktif dengan nilai parameter yang diubah
widgets.interactive(update_sir_birth_death,
    beta=widgets.FloatSlider(min=0.0001, max=1, step=0.0001, value=0.5, description='β'),
    gamma=widgets.FloatSlider(min=0.01, max=1, step=0.01, value=0.3, description='γ'),
    alpha=widgets.FloatSlider(min=0.0001, max=0.1, step=0.0001, value=0.01, description='α'),
    sigma=widgets.FloatSlider(min=0.0001, max=0.1, step=0.0001, value=0.01, description='σ'),
    S0=widgets.IntSlider(min=1, max=1000, step=1, value=997, description='S₀'),
    I0=widgets.IntSlider(min=1, max=100, step=1, value=3, description='I₀'),
    Tmax=widgets.IntSlider(min=10, max=200, step=10, value=150, description='T_max'))